AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'lib/templates/**/*'
    - 'lib/tasks/release.rake'
    - 'spec/**/*'
    - 'app/models/cache_version.rb'
    - 'Gemfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/UnneededPercentQ:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/PredicateName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/MutableConstant:
  Enabled: false

Metrics/LineLength:
  Max: 1200

Metrics/ClassLength:
  Max: 1200

Metrics/MethodLength:
  Max: 1200

Metrics/ModuleLength:
  Max: 1200

Metrics/BlockLength:
  Max: 1200

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/LambdaCall:
  Enabled: false
