FROM rubylang/ruby:3.0.0-preview1-bionic

RUN gem install bundler
RUN sed -i 's#http://deb.debian.org#https://mirrors.163.com#g' /etc/apt/sources.list && \
  apt update && apt install -y curl gnupg && \
  curl -sL https://deb.nodesource.com/setup_14.x |  bash - && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt update

RUN apt install -y ca-certificates nodejs cron socat curl git htop tzdata imagemagick nginx libnginx-mod-http-image-filter libnginx-mod-http-geoip  \
  build-essential ruby-dev openssl libpq-dev libxml2-dev libxslt-dev yarn

RUN curl https://get.acme.sh | sh
