defaults: &defaults
  app_name: "<%= ENV['app_name'] || 'Homeland' %>"
  # Plugin module, [topic,home,wiki,site,note,team,github,editor.code,press,jobs]
  modules: "<%= ENV['modules'] || 'all'  %>"
  # User profile module default: all [company,twitter,website,tagline,location,alipay,paypal,qq,weibo,wechat,douban,dingding,aliwangwang,facebook,instagram,dribbble,battle_tag,psn_id,steam_id]
  profile_fields: "<%= ENV['profile_fields'] || 'all' %>"
  domain: "<%= ENV['domain'] || 'localhost' %>"
  https: <%= ENV['https'] || 'true' %>
  admin_emails: <%= ENV['admin_emails'] || 'admin@admin.com' %>
  asset_host: "<%= ENV['asset_host'] %>"
  <% if ENV['rack_attack_limit'] == 'true' %>
  rack_attack:
    limit: <%= ENV['rack_attack_limit'] %>
    period: <%= ENV['rack_attack_period'] %>
  <% end %>
  upload_provider: "<%= ENV['upload_provider'] || 'file' %>" # can be  upyun/aliyun
  upload_access_id: "<%= ENV['upload_access_id'] %>" # or username
  upload_access_secret: "<%= ENV['upload_access_secret'] %>" # or upyun password
  upload_bucket: "<%= ENV['upload_bucket'] %>"
  upload_url: "<%= ENV['upload_url'] %>"
  upload_aliyun_internal: <%= ENV['upload_aliyun_internal'] == 'true' %>
  upload_aliyun_area: "<%= ENV['upload_aliyun_area'] %>"
  mailer_provider: "<%= ENV['mailer_provider'] || 'smtp' %>"
  mailer_sender: "<%= ENV['mailer_sender'] || 'no-reply@localhost' %>"
  mailer_options:
    <% if ENV['mailer_provider'] == 'postmark' %>
    api_key: '<%= ENV['mailer_options_api_key'] %>'
    <% else %>
    address: '<%= ENV['mailer_options_address'] %>'
    port: <%= ENV['mailer_options_port'] %>
    domain: '<%= ENV['mailer_options_domain'] %>'
    user_name: '<%= ENV['mailer_options_user_name'] %>'
    password: '<%= ENV['mailer_options_password'] %>'
    authentication: '<%= ENV['mailer_options_authentication'] %>'
    enable_starttls_auto: <%= ENV['mailer_options_enable_starttls_auto'] %>
    <% end %>
  sso:
    <% if ENV['sso_enable_provider'] != 'true' %>
    enable: <%= ENV['sso_enable'] || false %>
    <% else %>
    enable_provider: <%= ENV['sso_enable_provider'] || false %>
    <% end %>
    url: '<%= ENV['sso_url'] %>'
    secret: '<%= ENV['sso_secret'] %>'
  github_token: "<%= ENV['github_token'] %>"
  github_secret: "<%= ENV['github_secret'] %>"
  newbie_limit_time: 86400
  topic_create_limit_interval: 60
  topic_create_hour_limit_count: 10

development:
  <<: *defaults

test:
  <<: *defaults
  modules: 'all'
  profile_fields: 'all'
  upload_provider: "file"
  sso:
    enable: false
    enable_provider: false

production:
  <<: *defaults
